### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by JulioC** [martenbjork/sign-up-for-facebook#2]
Have you planned localizing this to other languages?

**Comment by martenbjork** [comment]
Not yet, but i'm open for it!

**Comment by ghost** [comment]
+1 for localization

**Comment by muki** [comment]
Sooo, we translated it to Slovenian and published it just now. We didin't include an internationalisation plugin though, just translated the whole thing "by hand".

https://uporabljajfacebook.si 

Our fork is available here https://github.com/danesjenovdan/sign-up-for-facebook

Thanks for all your work @martenbjork

**Comment by martenbjork** [comment]
@muki So cool! Well done 🥇 

(Let's see if there's more interest in translating. If so, it would probably make sense to build something smarter, like generating the site(s) from markdown files.)
