### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by madiodio** [martenbjork/sign-up-for-facebook#5]
The purpose of the project is commendable, too many people don't know yet what Facebook does with their data and how it recursively tracks them on the Internet. But as I'm writing this [Facebook has 2.2 billion monthly active users](https://www.statista.com/statistics/264810/number-of-monthly-active-facebook-users-worldwide/) so it's kind of difficult these days to find someone that hasn't signed up for Facebook yet. So I feel like this could have been `(Why You Should) Delete your Facebook Account` instead of `Sign Up For Facebook`. So the bullet point buttons could be `I'm not ok with this` and provide a link to delete your Facebook account as the final call to action button.

Just a suggestion, thanks!

**Comment by martenbjork** [comment]
Thanks for the suggestion. I think the name works for both groups. Existing users might ask themselves “knowing this, would I have signed up?” while non-users will learn more about Facebook before signing up.

As for changing the title and the button — I don't think it's _this_ site's job to encourage people to leave Facebook. It should be an education initiative, not a call to action.

**Comment by madiodio** [comment]
Ah got you, haven't thought about it. Keep it the good work!

**Comment by martenbjork** [comment]
Thanks! :)
