### ISSUE TITLE
Update SSL certificates

### ISSUE THREAD

**Issue by pabloab** [martenbjork/sign-up-for-facebook#7]
Let's Encrypt had expired. Error in the browser, tested with `curl -v` and with [ssllabs.com/ssltest](https://www.ssllabs.com/ssltest/).
```
Expires On	Sunday, June 24, 2018 at 12:00:09 PM
SHA-256 Fingerprint	C3 C9 AD E2 F3 7C 36 C0 65 25 60 56 95 D6 BA 52 CB D4 77 04 FF 1C 6F D9 CF 3D AF E1 42 82 BE 04
SHA-1 Fingerprint	5D 66 14 81 89 47 74 8C 2B 6B 66 A1 9A 5E ED 5A 8F 37 08 2E
```

**Comment by martenbjork** [comment]
Thanks @pabloab! I've been on vacation and missed the expiration. I'm working on fixing it. (Will take 1 day or so, I'm moving the site from Heroku -> GH Pages).
